p8105_hw1_hw2861
================
2022-09-17

Problem 1 I use the following code to load the penguins dataset

``` r
data("penguins", package = "palmerpenguins")
names(penguins)
```

    ## [1] "species"           "island"            "bill_length_mm"   
    ## [4] "bill_depth_mm"     "flipper_length_mm" "body_mass_g"      
    ## [7] "sex"               "year"

``` r
summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

``` r
penguins
```

    ## # A tibble: 344 × 8
    ##    species island    bill_length_mm bill_depth_mm flipper_…¹ body_…² sex    year
    ##    <fct>   <fct>              <dbl>         <dbl>      <int>   <int> <fct> <int>
    ##  1 Adelie  Torgersen           39.1          18.7        181    3750 male   2007
    ##  2 Adelie  Torgersen           39.5          17.4        186    3800 fema…  2007
    ##  3 Adelie  Torgersen           40.3          18          195    3250 fema…  2007
    ##  4 Adelie  Torgersen           NA            NA           NA      NA <NA>   2007
    ##  5 Adelie  Torgersen           36.7          19.3        193    3450 fema…  2007
    ##  6 Adelie  Torgersen           39.3          20.6        190    3650 male   2007
    ##  7 Adelie  Torgersen           38.9          17.8        181    3625 fema…  2007
    ##  8 Adelie  Torgersen           39.2          19.6        195    4675 male   2007
    ##  9 Adelie  Torgersen           34.1          18.1        193    3475 <NA>   2007
    ## 10 Adelie  Torgersen           42            20.2        190    4250 <NA>   2007
    ## # … with 334 more rows, and abbreviated variable names ¹​flipper_length_mm,
    ## #   ²​body_mass_g

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

``` r
mean(penguins$flipper_length_mm, na.rm = TRUE)
```

    ## [1] 200.9152

Based on the R outcome, There are 8 variables(ncol),they are “species”,
“island”, “bill_length_mm”, “bill_depth_mm”, “flipper_length_mm”,
“body_mass_g”, “sex”and”year”.

Also,There are 344(nrow) individuals in this dataset. The mean flipper
length of the dataset is 200.92.

Make a scatterplot

``` r
library(ggplot2)
ggplot(data=penguins,aes(x = bill_length_mm, y = flipper_length_mm,color=species))+ geom_point()
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_2861_files/figure-gfm/unnamed-chunk-2-1.png)<!-- -->

``` r
ggsave("scatter_plot.pdf", height = 4, width = 5)
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

Problem 2

X1 is the random sample x2 is the logical vector x3 is the character
vector x4 is the factor vector

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ✔ purrr   0.3.4      
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
example_df = tibble(
x1 = rnorm(10),
x2 = x1 > 0,
x3= c("a","b","c","d","e","f","g","h","i","k"),
x4 = factor(c("Small", "Medium", "Small", "Small","Large", "Large", "Medium","Large","Medium","Small"))
)
example_df
```

    ## # A tibble: 10 × 4
    ##        x1 x2    x3    x4    
    ##     <dbl> <lgl> <chr> <fct> 
    ##  1  1.62  TRUE  a     Small 
    ##  2 -0.460 FALSE b     Medium
    ##  3  1.67  TRUE  c     Small 
    ##  4 -2.67  FALSE d     Small 
    ##  5 -0.767 FALSE e     Large 
    ##  6  1.13  TRUE  f     Large 
    ##  7  0.690 TRUE  g     Medium
    ##  8  0.749 TRUE  h     Large 
    ##  9  0.482 TRUE  i     Medium
    ## 10  2.15  TRUE  k     Small

We take the mean of the variables

``` r
library(tidyverse)
mean_x1 = mean(pull(example_df,x1))
mean_x2 = mean(pull(example_df,x2))
mean_x3 = mean(pull(example_df,x3))
```

    ## Warning in mean.default(pull(example_df, x3)): argument is not numeric or
    ## logical: returning NA

``` r
mean_x4 = mean(pull(example_df,x4))
```

    ## Warning in mean.default(pull(example_df, x4)): argument is not numeric or
    ## logical: returning NA

The x1(a random sample) and x2(The logical vector) can be used to take
the mean. But the X3(character vector) and X4(factor vector) can Not be
used to take the mean.
